# 期刊和数据库配置文件

# API类型数据源
api_sources:
  arxiv:
    name: "arXiv"
    type: "api"
    base_url: "http://export.arxiv.org/api/query"
    search_params:
      search_query: "{keywords}"
      start: 0
      max_results: 10
      sortBy: "submittedDate"
      sortOrder: "descending"
    parser: "arxiv_parser"
    rate_limit: 3  # 每秒请求数限制

  springer:
    name: "Springer Nature"
    type: "api"
    base_url: "https://api.springernature.com/metadata/json"
    search_params:
      q: "{keywords}"
      api_key: "YOUR_API_KEY"  # 需要替换为实际的API密钥
      s: 1  # 起始位置
      p: 10  # 每页结果数
    parser: "springer_parser"
    rate_limit: 2

  elsevier:
    name: "ScienceDirect"
    type: "api"
    base_url: "https://api.elsevier.com/content/search/sciencedirect"
    search_params:
      query: "{keywords}"
      apiKey: "YOUR_API_KEY"  # 需要替换为实际的API密钥
      count: 10
    parser: "elsevier_parser"
    rate_limit: 2

# RSS类型数据源
rss_sources:
  nature:
    name: "Nature"
    type: "rss"
    url: "https://www.nature.com/nature.rss"
    parser: "nature_rss_parser"

  science:
    name: "Science"
    type: "rss"
    url: "https://www.science.org/rss/journal/science.xml"
    parser: "science_rss_parser"

  advanced_materials:
    name: "Advanced Materials"
    type: "rss"
    url: "https://advanced.onlinelibrary.wiley.com/action/showFeed?jc=15214095&type=etoc&feed=rss"
    parser: "wiley_rss_parser"

  nature_photonics:
    name: "Nature Photonics"
    type: "rss"
    url: "https://www.nature.com/nphoton.rss"
    parser: "nature_rss_parser"

  advanced_functional_materials:
    name: "Advanced Functional Materials"
    type: "rss"
    url: "https://advanced.onlinelibrary.wiley.com/action/showFeed?jc=16163028&type=etoc&feed=rss"
    parser: "wiley_rss_parser"

  advanced_energy_materials:
    name: "Advanced Energy Materials"
    type: "rss"
    url: "https://advanced.onlinelibrary.wiley.com/action/showFeed?jc=16146840&type=etoc&feed=rss"
    parser: "wiley_rss_parser"

  energy_environmental_science:
    name: "Energy & Environmental Science"
    type: "rss"
    url: "https://pubs.rsc.org/en/journals/journalissues/ee?issueid=current&type=current&issnprint=1754-5692"
    parser: "rsc_rss_parser"

  acs_applied_materials:
    name: "ACS Applied Materials & Interfaces"
    type: "rss"
    url: "https://pubs.acs.org/action/showFeed?type=etoc&feed=rss&jc=aamick"
    parser: "acs_rss_parser"

# 网页爬取类型数据源（用于无API或RSS的情况）
web_sources:
  sciencedirect:
    name: "ScienceDirect"
    type: "web"
    base_url: "https://www.sciencedirect.com/search"
    search_params:
      qs: "{keywords}"
      show: 100
      sortBy: "date"
    parser: "sciencedirect_web_parser"
    rate_limit: 1
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    selectors:
      article_container: "div.result-item"
      title: "h2"
      authors: "div.Authors"
      abstract: "div.abstract-text"
      link: "h2 a"
      date: "div.publication-date"
