name: Daily Research Paper Tracker

on:
  schedule:
    - cron: '0 0 * * *'   # 每天0点UTC自动运行
  workflow_dispatch:       # 允许手动运行

jobs:
  run-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 运行主程序
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          python src/main.py
